### ISSUE TITLE
When build with version >= 3.4.3 I'm getting the following error on import: The file "filename.pbiviz" isn't a valid custom visual.

### ISSUE THREAD

**Issue by JipAccobat** [microsoft/PowerBI-visuals-tools#402] opened 2021-12-08 13:57 UTC
Hello,

After updating to version 3.4.3 or above of the build tool I'm getting the following error when trying to import packages build with it:
![image](https://user-images.githubusercontent.com/70894598/145220508-201c3497-bdd1-4b7f-bf1e-160211fd6821.png)

/Jimmy

**Comment by Demonkratiy** [comment] 2021-12-09 19:52
Hello @JipAccobat, is this project is private or can I try to test it?

**Comment by zBritva** [comment] 2021-12-09 20:08
@JipAccobat it seems that GUID contains whitespace. Could you check it?

**Comment by JipAccobat** [comment] 2021-12-10 07:38
@Demonkratiy the visual project is private.

@zBritva the GUID doesn't contain whitespace:
"guid": "accoPLANNING_4DAA52ABFBF441E2A7898A79384CAFA9_test",
![image](https://user-images.githubusercontent.com/70894598/145535558-7b238ac8-c1d1-470d-b1c1-dab01db8b95a.png)

**Comment by Melethainiel** [comment] 2021-12-10 08:21
I have the same here. My last version on the visual with v3.3.2 is working fine and since I updated to 4.0.0 I got the same error

**Comment by Demonkratiy** [comment] 2021-12-10 13:40
@Melethainiel, does your visual project is also private and you can't share it with me to test?

**Comment by iMicknl** [comment] 2021-12-10 16:58
I can reproduce with my project, which is public: https://github.com/iMicknl/powerbi-botframework-chat-transcripts. @Demonkratiy you can use this for debugging. And feel free to ping me internally as well (mivleesh).

See https://github.com/iMicknl/powerbi-botframework-chat-transcripts/issues/114 for context.

**Comment by Melethainiel** [comment] 2021-12-11 16:46
> @Melethainiel, does your visual project is also private and you can't share it with me to test?

Sure, I’ll give you access next monday

**Comment by nishantjainuk** [comment] 2021-12-12 09:41
I am also getting the same issue. However, it works on the browser. The issue is only with Desktop

**Comment by Melethainiel** [comment] 2021-12-13 07:06
@Demonkratiy you can find the repo [here](https://github.com/Melethainiel/pbiSvgDrawer)

**Comment by Demonkratiy** [comment] 2021-12-13 10:01
@iMicknl , @Melethainiel , thanks for provided source code. I think I found possible issue, it starts from tools version 3.4.3. 
We will prepare a fix soon. As for right now, please use version 3.4.2, it should work.

**Comment by Melethainiel** [comment] 2021-12-13 12:29
@Demonkratiy it’s working fine with 3.4.2.

**Comment by iMicknl** [comment] 2021-12-19 21:01
@Demonkratiy any estimation when a fix will be released?

**Comment by Demonkratiy** [comment] 2021-12-21 08:23
Yes sorry for a delay. Fix version is published - v 4.0.2. Please use it for now.

**Comment by iMicknl** [comment] 2021-12-21 08:46
I can confirm that 4.0.2 fixes the issue. Thanks for mitigating this issue.

**Closed** 2021-12-22 08:35 UTC

**Comment by ashfaqdawood** [comment] 2022-04-04 19:04
This issue seems to be occurring if we create a custom visual using "powerbi-visuals-webpack-plugin" version 3.0.0 without using the out of the box "pbiviz new" flow.
