### ISSUE TITLE
Format Objects not visible in DebugVisual

### ISSUE THREAD

**Issue by Mcburn** [Microsoft/PowerBI-visuals-tools#43] opened 2016-10-07 08:22 UTC
Hey,

since last friday i did not see the format objects in the debug visual.
But when i package the Project and import that visual in the same report,
i can see that objects.

But the objects reset every update. So maybe this is a another problem by my side but i can not debug this, in the Debug Visual.

Is that a problem from the Tool or from Power BI? #

**Comment by raananzvi** [comment] 2016-10-13 07:34
I'm afraid the issue is in the Power BI code and not the tool.

**Comment by raananzvi** [comment] 2016-10-26 08:16
The fix was committed to the Power BI service, but it will take several weeks for it to propagate to the production service.

**Closed by raananzvi** 2016-10-26 08:16 UTC
