### ISSUE TITLE
SSL certificate is considered invalid by Chrome 58

### ISSUE THREAD

**Issue by sarafankit** [Microsoft/PowerBI-visuals-tools#99] opened 2017-05-18 02:56 UTC
My visual was failing to load in latest Chrome, so tried accessing the https://localhost:8080/assets/logo.txt path directly. Chrome showed the following error:

> Your connection is not private
> Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID
> 
>This server could not prove that it is localhost; its security certificate is from [missing_subjectAltName]. This may be caused by a misconfiguration or an attacker intercepting your connection. Learn more.

The issue seems to be happening because Chrome has deprecated support for commonName matching [https://www.chromestatus.com/features/4981025180483584](https://www.chromestatus.com/features/4981025180483584)

Some additional info: [https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/](https://www.chromestatus.com/features/4981025180483584)

**Comment by joergplewe** [comment] 2017-05-23 07:09
Same for me. Firefox still allows access after creating an exception to accept the self-signed certificate. Edge doesn't complain at all.

**Comment by mpbastos** [comment] 2017-05-23 23:23
I have the same issue. Edge allow the access but I get an another error not related to certificate.

**Comment by jonbgallant** [comment] 2017-05-24 20:35
I got this as well.
![image](https://cloud.githubusercontent.com/assets/2163001/26424354/cd1742e8-4085-11e7-81c8-6ad6c52cbe91.png)


![image](https://cloud.githubusercontent.com/assets/2163001/26424360/d14cfc68-4085-11e7-9c2b-13b74f000861.png)

Works in IE.

**Comment by jonbgallant** [comment] 2017-05-24 21:15
The steps here got me past this issue: https://github.com/Microsoft/PowerBI-visuals-tools/issues/20#issuecomment-303068862

**Comment by ignatvilesov** [comment] 2017-05-25 06:40
Duplicate of #20

**Closed by ignatvilesov** 2017-05-25 06:40 UTC
