### ISSUE TITLE
enumerateObjectInstances with containers and instances

### ISSUE THREAD

**Issue by saifulhq** [microsoft/PowerBI-visuals-tools#283] opened 2019-09-05 06:08 UTC
with 3.1.5 I'm want combo box with this code
`

            const containerIdx = enumerationObject.containers.push({ displayName: currentColumn.displayName }) - 1;
            enumerationObject.instances.push({
                containerIdx,
                objectName,
                properties: {
                    isMasking: VisualHelper.getValue<boolean>(currentColumn.objects, objectName, "isMasking", false),
                    maskingType: VisualHelper.getValue<string>(currentColumn.objects, objectName, "maskingType", "1"),
                    headerAlias: VisualHelper.getValue<string>(currentColumn.objects, objectName, "headerAlias", currentColumn.displayName),
                    color: VisualHelper.getValue<string>(currentColumn.objects, objectName, "color", UISetting.DEFAULT_FOREGROUND),
                    background: VisualHelper.getValue<string>(currentColumn.objects, objectName, "background", UISetting.DEFAULT_COLOR)
                },
                selector: { metadata: currentColumn.queryName }
            });`

but the result just show the empty combo box, image can see at [https://community.powerbi.com/t5/Developer/combo-box-with-dynamic-value/m-p/781220#M20581](url)

**Comment by dm-p** [comment] 2019-12-10 18:41
Emailed the team last week with the same question and haven't heard back yet, but came across this and looks like it's not just me having issues with getting it to work. I've compiled Power KPI locally and the same thing happens as above, yet the marketplace version of this visual works as expected. How can we get this working for our own visuals?

**Comment by jorpheus** [comment] 2020-02-25 12:35
Hit this issue with Power KPI yesterday. Just located this open issue today. Has this been confirmed as an issue by the team? Only really asking to see if there is a "work around" or if it's a case of waiting for a fix in a future release?

**Comment by helen508light** [comment] 2020-03-10 15:14
There is no ETA for now

**Comment by djpirra** [comment] 2020-12-10 12:52
When will this be implemented? Been requesting this feature to the team for more than 2 years now.
I believe this is one of the most wanted features in Custom Visuals and it would enable loads of new and advanced scenarios.

**Comment by sranins** [comment] 2020-12-14 13:18
Hi
This bug has been fixed and  will reach production by mid January.
Thanks

**Comment by AviSander** [comment] 2020-12-14 15:29
hi , 
    a fix has been checked in, and should be available in production by mid January.
thx.

**Comment by staticset** [comment] 2021-02-11 12:11
hi
when it will be?

**Comment by djpirra** [comment] 2021-03-08 06:48
Can we get a working example of this?
I am able to populate the dropdown now... but don't understand how to read the values per option now...

Thanks

**Comment by AleksSavelev** [comment] 2023-04-27 08:09
We recommend everyone to use new [format pane api](https://learn.microsoft.com/en-us/power-bi/developer/visuals/format-pane)

**Closed by AleksSavelev** 2023-04-27 08:09 UTC
Labels: bug
