### ISSUE TITLE
Can't scroll in Format menu

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#328] opened 2020-08-13 09:04 UTC
In some cases, it's not possible to scroll further in the Format menu, thus some some settings can't be seen.
![image](https://user-images.githubusercontent.com/8909363/90115704-bc0a3b80-dd54-11ea-9328-270b14269bcb.png)

**Comment by helen508light** [comment] 2020-08-31 19:01
@KoBe321 Please attach report file to reproduce it

**Comment by KoBe321** [comment] 2020-09-08 11:10
[settings_no_scroll.zip](https://github.com/microsoft/PowerBI-visuals-tools/files/5187492/settings_no_scroll.zip)

How to reproduce:
1. In the Settings search bar, search for "tot".
2. Close the 4 opened accordion.
3. Open the "Totals" accordion.
4. Scroll down.
5. You won't be able to see the last accordion "Dynaminc Update Total Values".

**Comment by KoBe321** [comment] 2020-11-20 09:17
Hi, any update on this?

**Comment by helen508light** [comment] 2021-03-02 15:19
@KoBe321 
on which service(desktop, PowerBI report service, web service) do you got this? 
Step 5 is not reproducible for us - seems to work correct on desktop and web service.
Could you please add additional info?

**Comment by KoBe321** [comment] 2021-03-05 07:54
@helen508light 
My report is here: https://app.powerbi.com/

**Comment by AleksSavelev** [comment] 2023-04-27 08:21
Closing this issue due to age, feel free to open it again if the issue reproduces

**Closed by AleksSavelev** 2023-04-27 08:21 UTC
Labels: bug
