### ISSUE TITLE
update() not triggering

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#332] opened 2020-09-08 12:28 UTC
This bug report  is based on these posts: [LINK](https://community.powerbi.com/t5/Developer/Visual-update-not-triggered-when-switching-from-Reading-to-Edit/m-p/423405/highlight/false#M12737)

In some cases update() is not triggered. 
We noticed that it might be in connetion with the size of the report or visual. It happens when a "resize" event is not fired.
When going to Edit mode from View mode after saving the report and refreshing the page, upate() is not triggered.
As an other user detected this is also the case if the "Actual Size" report setting is used.

**Comment by AleksSavelev** [comment] 2023-04-27 08:23
Closing this issue due to age, feel free to open it again if the issue reproduces

**Closed by AleksSavelev** 2023-04-27 08:23 UTC
